import React from "react";
import ReactDOM from "react-dom";
// import App from "./App";
// import Main from "./Routing/Main";
import { BrowserRouter } from "react-router-dom";
// import Api from "./Api/api";
// import ContactHooks from "./Hooks/contactHooks";
import "bootstrap/dist/css/bootstrap.min.css";
// import Hooks from "./Hooks/Hooks";
// import Int from "./Hooks/int";
// import Counter from "./hooks/counter";
// import Ref from "./compontent/Ref";
// import { ProductProvider } from "./context";
// import { Provider } from "react-redux";
// import store from "./redux/store";
// import Counter from "./redux/counter/counter";
import App from "./App";
import Routing from "./movies/Routing";

ReactDOM.render(<App />, document.getElementById("root"));
